name = "personal-notes"
type = "webpack"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

[site]
bucket = "./build"
entry-point = "workers-site"

[build]
command = "npm run build"
output_dir = "build"

[env.production]
zone_id = "8af8578b2148f84db3b5d7d3fe77ee44"
route = "jilu.20204.us.kg/*"

# KV 绑定
kv_namespaces = [
  { binding = "SUBMISSIONS", id = "SUBMISSIONS" }
]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "su"
database_id = "bea853b9-6f64-4dfa-a785-2efbc1d7a446"

[[d1_databases]]
binding = "IP_DB"
database_name = "ip"
database_id = "97c2a0fe-8657-4b0e-a5fd-856c6e607b51"

[env.production.vars]
ENABLE_IP_GEOLOCATION = true