name = "personal-notes"
type = "webpack"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

[site]
bucket = "./build"
entry-point = "workers-site"

[env.production]
zone_id = "YOUR_ZONE_ID"
route = "20204.us.kg/*"

[vars]
SMTP_HOST = "smtphz.qiye.163.com"
SMTP_PORT = "465"
SMTP_USER = "su@one-mail.us.kg" 