# 项目基本配置
name = "dream-survey"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Pages 配置
[build]
command = "CI=false npm run build"
output_dir = "build"

[site]
bucket = "./build"
entry-point = "workers-site"

# 环境变量
[vars]
TURNSTILE_SECRET_KEY = "0x4AAAAAAA2BDP_0hTzFV8HfROVfaq5miog"

# 路由配置
[env.production]
routes = [
  "jilu.20204.us.kg/*",
  "jilu.20204.us.kg/jieshao",
  "jilu.20204.us.kg/queren",
  "jilu.20204.us.kg/error"
]

# 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "dream_survey"
database_id = "xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"

[[d1_databases]]
binding = "IP_DB"
database_name = "ip_records"
database_id = "yyyyy-yyyy-yyyy-yyyy-yyyyyyyyyy"